name = "pokemon"
main = "worker.ts"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "public"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "pokemon-battle-db"
database_id = "81b2d13f-2dd9-469d-939b-d5324aba0bf6"

[durable_objects]
bindings = [
  { name = "BATTLE_ROOM", class_name = "BattleRoom" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["BattleRoom"]
